CREATE TABLE USERS (
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME   VARCHAR(60) NOT NULL,
    LASTNAME    VARCHAR(60) NOT NULL,
    BIRTHDAY   DATE NOT NULL
);

INSERT INTO USERS (FIRSTNAME, LASTNAME, BIRTHDAY) VALUES
    ('Mock', 'Petrov', '2000-04-03'),
    ('Mock', 'Bulkin', '1987-11-27'),
    ('Mock', 'Antonova', '2004-05-17');